




import { Language, TranslationContent, Category } from './types';

// Updated fallback images with reliable sources
const FALLBACK_IMAGES: Record<string, string> = {
  beauty: 'https://images.pexels.com/photos/3762466/pexels-photo-3762466.jpeg?auto=compress&cs=tinysrgb&w=300',
  apparel: 'https://images.pexels.com/photos/996329/pexels-photo-996329.jpeg?auto=compress&cs=tinysrgb&w=300',
  electronics: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=300',
  home: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=300',
  grocery: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=300',
  vehicles: 'https://images.pexels.com/photos/12222662/pexels-photo-12222662.jpeg?auto=compress&cs=tinysrgb&w=300',
  toys: 'https://images.pexels.com/photos/3662849/pexels-photo-3662849.jpeg?auto=compress&cs=tinysrgb&w=300',
  sports: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=300',
  business: 'https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=300',
  pets: 'https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg?auto=compress&cs=tinysrgb&w=300',
  arts: 'https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=300',
  health: 'https://images.pexels.com/photos/365209/pexels-photo-365209.jpeg?auto=compress&cs=tinysrgb&w=300',
  default: 'https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg?auto=compress&cs=tinysrgb&w=300'
};

export const CATEGORY_DATA: Category[] = [
  {
    id: 'beauty',
    subcategories: [
      { id: 'face', image: 'https://images.pexels.com/photos/3762466/pexels-photo-3762466.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'makeup', image: 'https://images.pexels.com/photos/457701/pexels-photo-457701.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'hair', image: 'https://images.pexels.com/photos/3993442/pexels-photo-3993442.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'korean', image: 'https://images.pexels.com/photos/4041391/pexels-photo-4041391.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'body', image: 'https://images.pexels.com/photos/8533268/pexels-photo-8533268.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'nails', image: 'https://images.pexels.com/photos/939836/pexels-photo-939836.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'men', image: 'https://images.pexels.com/photos/3998429/pexels-photo-3998429.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'devices', image: 'https://images.pexels.com/photos/6621435/pexels-photo-6621435.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'organic', image: 'https://images.pexels.com/photos/6763174/pexels-photo-6763174.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'apparel',
    subcategories: [
      { id: 'women_clothing', image: 'https://images.pexels.com/photos/974911/pexels-photo-974911.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'men_clothing', image: 'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'kids_clothing', image: 'https://images.pexels.com/photos/1620760/pexels-photo-1620760.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'sportswear', image: 'https://images.pexels.com/photos/4327027/pexels-photo-4327027.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'underwear', image: 'https://images.pexels.com/photos/264726/pexels-photo-264726.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'shoes', image: 'https://images.pexels.com/photos/1598505/pexels-photo-1598505.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'winter', image: 'https://images.pexels.com/photos/3317434/pexels-photo-3317434.jpeg?auto=compress&cs=tinysrgb&w=300' }, 
      { id: 'bags', image: 'https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'accessories', image: 'https://images.pexels.com/photos/265906/pexels-photo-265906.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'electronics',
    subcategories: [
      { id: 'smartphones', image: 'https://images.pexels.com/photos/788946/pexels-photo-788946.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'computers', image: 'https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'audio', image: 'https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'smartwatch', image: 'https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg?auto=compress&cs=tinysrgb&w=300' }, 
      { id: 'camera', image: 'https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'gaming', image: 'https://images.pexels.com/photos/3945659/pexels-photo-3945659.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'kitchen_appliances', image: 'https://images.pexels.com/photos/211760/pexels-photo-211760.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'home_appliances', image: 'https://images.pexels.com/photos/9267566/pexels-photo-9267566.jpeg?auto=compress&cs=tinysrgb&w=300' }, 
      { id: 'personal_care', image: 'https://images.pexels.com/photos/3993398/pexels-photo-3993398.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'home',
    subcategories: [
      { id: 'bedding', image: 'https://images.pexels.com/photos/164595/pexels-photo-164595.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'kitchenware', image: 'https://images.pexels.com/photos/6996086/pexels-photo-6996086.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'storage', image: 'https://images.pexels.com/photos/4569340/pexels-photo-4569340.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'lighting', image: 'https://images.pexels.com/photos/1123262/pexels-photo-1123262.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'decor', image: 'https://images.pexels.com/photos/1090638/pexels-photo-1090638.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'garden', image: 'https://images.pexels.com/photos/4197935/pexels-photo-4197935.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'bathroom', image: 'https://images.pexels.com/photos/545013/pexels-photo-545013.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'tools', image: 'https://images.pexels.com/photos/162553/keys-workshop-mechanic-tools-162553.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'grocery',
    subcategories: [
      { id: 'snacks', image: 'https://images.pexels.com/photos/1580466/pexels-photo-1580466.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'coffee_tea', image: 'https://images.pexels.com/photos/312418/pexels-photo-312418.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'grain_oil', image: 'https://images.pexels.com/photos/33525/olive-oil-salad-dressing-cooking-olive.jpg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'health_food', image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'canned', image: 'https://images.pexels.com/photos/6207297/pexels-photo-6207297.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'nuts', image: 'https://images.pexels.com/photos/3735192/pexels-photo-3735192.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'baking', image: 'https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'drinks', image: 'https://images.pexels.com/photos/3008/drinks-supermarket-cans-beverage.jpg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'vehicles',
    subcategories: [
      { id: 'car_electronics', image: 'https://images.pexels.com/photos/2265486/pexels-photo-2265486.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'car_interior', image: 'https://images.pexels.com/photos/1519192/pexels-photo-1519192.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'cleaning', image: 'https://images.pexels.com/photos/4489704/pexels-photo-4489704.jpeg?auto=compress&cs=tinysrgb&w=300' }, 
      { id: 'repair_tools', image: 'https://images.pexels.com/photos/4489765/pexels-photo-4489765.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'oil', image: 'https://images.pexels.com/photos/3806249/pexels-photo-3806249.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'motorcycle', image: 'https://images.pexels.com/photos/2116475/pexels-photo-2116475.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'toys',
    subcategories: [
      { id: 'educational', image: 'https://images.pexels.com/photos/3662973/pexels-photo-3662973.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'dolls', image: 'https://images.pexels.com/photos/208821/pexels-photo-208821.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'remote_control', image: 'https://images.pexels.com/photos/256417/pexels-photo-256417.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'outdoor_toys', image: 'https://images.pexels.com/photos/3662849/pexels-photo-3662849.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'puzzles', image: 'https://images.pexels.com/photos/269399/pexels-photo-269399.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'plush', image: 'https://images.pexels.com/photos/701016/pexels-photo-701016.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'creative', image: 'https://images.pexels.com/photos/114907/pexels-photo-114907.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'models', image: 'https://images.pexels.com/photos/163696/toy-car-toy-box-mini-163696.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'sports',
    subcategories: [
      { id: 'fitness', image: 'https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'outdoor', image: 'https://images.pexels.com/photos/2396056/pexels-photo-2396056.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'fishing', image: 'https://images.pexels.com/photos/294674/pexels-photo-294674.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'team_sports', image: 'https://images.pexels.com/photos/3621104/pexels-photo-3621104.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'cycling', image: 'https://images.pexels.com/photos/248547/pexels-photo-248547.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'swimming', image: 'https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'camping', image: 'https://images.pexels.com/photos/1061640/pexels-photo-1061640.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'yoga', image: 'https://images.pexels.com/photos/4056535/pexels-photo-4056535.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'business',
    subcategories: [
      { id: 'office_supplies', image: 'https://images.pexels.com/photos/733857/pexels-photo-733857.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'equipment', image: 'https://images.pexels.com/photos/1957478/pexels-photo-1957478.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'packaging', image: 'https://images.pexels.com/photos/4439425/pexels-photo-4439425.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'furniture', image: 'https://images.pexels.com/photos/1957477/pexels-photo-1957477.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'printing', image: 'https://images.pexels.com/photos/2253573/pexels-photo-2253573.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'stationery', image: 'https://images.pexels.com/photos/457713/pexels-photo-457713.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'pets',
    subcategories: [
      { id: 'dog_food', image: 'https://images.pexels.com/photos/58997/pexels-photo-58997.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'cat_food', image: 'https://images.pexels.com/photos/208984/pexels-photo-208984.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'pet_toys', image: 'https://images.pexels.com/photos/45170/kittens-cat-cat-puppy-rush-45170.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'pet_health', image: 'https://images.pexels.com/photos/6234603/pexels-photo-6234603.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'aquarium', image: 'https://images.pexels.com/photos/2156311/pexels-photo-2156311.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'small_animals', image: 'https://images.pexels.com/photos/326012/pexels-photo-326012.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'grooming', image: 'https://images.pexels.com/photos/1364756/pexels-photo-1364756.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'pet_clothes', image: 'https://images.pexels.com/photos/4588047/pexels-photo-4588047.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'arts',
    subcategories: [
      { id: 'painting', image: 'https://images.pexels.com/photos/102127/pexels-photo-102127.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'sewing', image: 'https://images.pexels.com/photos/461035/pexels-photo-461035.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'knitting', image: 'https://images.pexels.com/photos/3738095/pexels-photo-3738095.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'jewelry_making', image: 'https://images.pexels.com/photos/744667/pexels-photo-744667.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'pottery', image: 'https://images.pexels.com/photos/3094035/pexels-photo-3094035.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'scrapbooking', image: 'https://images.pexels.com/photos/4226876/pexels-photo-4226876.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  },
  {
    id: 'health',
    subcategories: [
      { id: 'supplements', image: 'https://images.pexels.com/photos/365209/pexels-photo-365209.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'first_aid', image: 'https://images.pexels.com/photos/4047184/pexels-photo-4047184.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'medical_devices', image: 'https://images.pexels.com/photos/6303590/pexels-photo-6303590.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'massage', image: 'https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'optical', image: 'https://images.pexels.com/photos/701877/pexels-photo-701877.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'sexual_wellness', image: 'https://images.pexels.com/photos/162568/oil-massage-relaxation-relax-162568.jpeg?auto=compress&cs=tinysrgb&w=300' },
      { id: 'mobility', image: 'https://images.pexels.com/photos/7298640/pexels-photo-7298640.jpeg?auto=compress&cs=tinysrgb&w=300' }
    ]
  }
];

export const TRANSLATIONS: Record<Language, TranslationContent> = {
  [Language.ZH]: {
    nav: {
      logo: 'RuSample',
      searchPlaceholder: '搜索产品或类别...',
      login: '登录',
      signup: '注册',
      categories: '全部分类'
    },
    hero: {
      headline: '连接全球买家，免费试用顶级产品',
      subheadline: 'RuSample 帮助品牌将新产品送到目标受众手中。加入我们的社区，开始您的发现之旅。',
      ctaButton: '开始试用',
      badgeTrial: '14天免费试用',
      badgeUsers: '10k+ 活跃用户'
    },
    search: {
      resultsFor: '搜索',
      noResults: '未找到相关结果',
      total: '共',
      results: '条结果'
    },
    auth: {
      loginTitle: '欢迎回来',
      signupTitle: '创建账户',
      notMember: '还不是会员？',
      alreadyMember: '已经是会员？',
      registerLink: '立即注册',
      loginLink: '立即登录',
      emailLabel: '电子邮件',
      emailPlaceholder: 'name@company.com',
      passwordLabel: '密码',
      passwordPlaceholder: '••••••••',
      forgotPassword: '忘记密码？',
      submitLogin: '登录',
      submitSignup: '注册',
      continueGoogle: '使用 Google 继续',
      continueFacebook: '使用 Facebook 继续',
      continueApple: '使用 Apple 继续',
      continueVK: '使用 VK 继续',
      leftHeadline: '数千种免费样品，尽在掌握',
      getAppButton: '获取 App',
      roleBuyer: '我是买家',
      roleSeller: '我是卖家'
    },
    seller: {
      dashboard: '卖家中心',
      overview: '概览',
      products: '产品管理',
      orders: '订单管理',
      analytics: '数据分析',
      settings: '设置',
      createProduct: '发布产品',
      productTitle: '产品名称',
      productDesc: '产品描述',
      uploadMedia: '上传图片/视频',
      uploadHint: '支持 JPG, PNG, MP4',
      quantity: '分发数量',
      platformLinks: '平台链接',
      ozonLink: 'Ozon 链接',
      wbLink: 'Wildberries 链接',
      reviewReq: '测评要求',
      reqPhoto: '图片测评',
      reqVideo: '视频测评',
      publish: '发布',
      cancel: '取消',
      activeProducts: '活跃产品',
      totalReviews: '总评价数',
      reviewRate: '回评率',
      pendingOrders: '待处理订单',
      customerRating: '买家评分',
      recentProducts: '最近产品',
      status: '状态',
      actions: '操作',
      viewReviews: '查看评价',
      shipBy: '发货截止',
      markShipped: '确认发货',
      profileSettings: '店铺信息',
      shopName: '店铺名称',
      shopNamePlaceholder: '例如：最佳美妆',
      contactEmail: '联系邮箱',
      phoneNumber: '联系电话',
      saveChanges: '保存更改',
      security: '账户安全',
      changePassword: '修改密码',
      notifications: '消息通知',
      traffic: '流量统计',
      conversionRate: '转化率',
      dailyViews: '日访问量',
      recentReviews: '最新评价',
      ratingDistribution: '评分分布',
      topProducts: '热门产品',
      totalViews: '总浏览量',
      sampleRequests: '申请总数',
      avgRating: '平均评分',
      currentPassword: '当前密码',
      newPassword: '新密码',
      confirmPassword: '确认新密码',
      orderUpdates: '订单更新通知',
      reviewAlerts: '评价提醒',
      marketingEmails: '营销邮件',
      logout: '退出登录',
      membership: '会员订阅',
      planStatus: '当前计划',
      daysRemaining: '剩余天数',
      upgradeToPro: '升级会员',
      trialExpired: '试用期已结束',
      paymentRequired: '您需要订阅会员才能发布新产品。',
      monthlyPlan: '月付计划',
      yearlyPlan: '年付计划',
      selectPayment: '选择支付方式',
      payNow: '立即支付',
      bestValue: '最超值',
      billingCycle: '账单周期',
      paymentMethods: {
        alipay: '支付宝',
        wechat: '微信支付',
        card: '信用卡/借记卡'
      }
    },
    buyer: {
      dashboard: '买家中心',
      browse: '浏览样品',
      mySamples: '我的样品',
      inbox: '消息通知',
      settings: '设置',
      requestSample: '申请样品',
      confirmReceipt: '确认收货',
      writeReview: '撰写评价',
      reviewBy: '评价截止',
      daysLeft: '天剩余',
      overdue: '已逾期',
      reviewed: '已评价',
      outOfStock: '暂时缺货',
      waitingShipment: '等待发货',
      welcomeBack: '欢迎回来',
      availableSamples: '可用样品',
      profile: '个人资料',
      shippingAddress: '收货地址',
      security: '账户安全',
      notifications: '通知设置',
      fullName: '完整姓名',
      displayName: '显示昵称',
      gender: '性别',
      birthDate: '出生日期',
      bio: '个人简介',
      addressLine1: '地址第一行',
      city: '城市',
      state: '州/省',
      zipCode: '邮政编码',
      country: '国家',
      saveChanges: '保存更改',
      logout: '退出登录'
    },
    categories: {
      beauty: '美妆护肤',
      apparel: '服饰鞋包',
      electronics: '数码家电',
      home: '家居生活',
      grocery: '食品饮料',
      vehicles: '汽车用品',
      toys: '玩具模型',
      sports: '运动户外',
      business: '办公用品',
      pets: '宠物用品',
      arts: '工艺美术',
      health: '医疗健康',
      // Subcategories
      face: '面部护理', makeup: '彩妆香氛', hair: '洗护发', korean: '韩系护肤', body: '身体护理', nails: '美甲', men: '男士护理', devices: '美容仪器', organic: '有机护肤',
      women_clothing: '女装', men_clothing: '男装', kids_clothing: '童装', sportswear: '运动服', underwear: '内衣家居', shoes: '鞋靴', winter: '冬装', bags: '箱包', accessories: '配饰',
      smartphones: '手机', computers: '电脑办公', audio: '影音娱乐', smartwatch: '智能穿戴', camera: '摄影摄像', gaming: '游戏电竞', kitchen_appliances: '厨房电器', home_appliances: '生活电器', personal_care: '个护健康',
      bedding: '家纺', kitchenware: '厨具', storage: '收纳', lighting: '灯具', decor: '装饰', garden: '园艺', bathroom: '卫浴', tools: '五金工具',
      snacks: '休闲零食', coffee_tea: '茶咖冲饮', grain_oil: '粮油调味', health_food: '营养保健', canned: '方便速食', nuts: '坚果炒货', baking: '烘焙原料', drinks: '饮料',
      car_electronics: '车载电器', car_interior: '内饰', cleaning: '洗护美容', repair_tools: '维修工具', oil: '机油', motorcycle: '摩托车',
      educational: '益智早教', dolls: '娃娃', remote_control: '遥控模型', outdoor_toys: '户外玩具', puzzles: '拼图', plush: '毛绒玩具', creative: '创意DIY', models: '手办模型',
      fitness: '健身器材', outdoor: '户外装备', fishing: '垂钓', team_sports: '球类', cycling: '骑行', swimming: '游泳', camping: '露营', yoga: '瑜伽',
      office_supplies: '办公文具', equipment: '办公设备', packaging: '包装耗材', furniture: '办公家具', printing: '打印耗材', stationery: '学生文具',
      dog_food: '狗粮', cat_food: '猫粮', pet_toys: '宠物玩具', pet_health: '宠物健康', aquarium: '水族', small_animals: '小宠', grooming: '洗护美容', pet_clothes: '宠物服饰',
      painting: '绘画', sewing: '缝纫', knitting: '编织', jewelry_making: '珠宝DIY', pottery: '陶艺', scrapbooking: '手账',
      supplements: '营养补充', first_aid: '急救护理', medical_devices: '家用医疗', massage: '按摩理疗', optical: '眼镜/隐形', sexual_wellness: '两性健康', mobility: '康复辅助'
    }
  },
  [Language.EN]: {
    nav: {
      logo: 'RuSample',
      searchPlaceholder: 'Search for products or categories...',
      login: 'Log In',
      signup: 'Sign Up',
      categories: 'All Categories'
    },
    hero: {
      headline: 'Connect with global brands, try products for free',
      subheadline: 'RuSample helps brands get new products into the hands of their target audience. Join our community and start your journey of discovery.',
      ctaButton: 'Start Trying',
      badgeTrial: '14-Day Free Trial',
      badgeUsers: '10k+ Active Users'
    },
    search: {
      resultsFor: 'Search results for',
      noResults: 'No results found',
      total: 'Total',
      results: 'results'
    },
    auth: {
      loginTitle: 'Welcome Back',
      signupTitle: 'Create Account',
      notMember: 'Not a member?',
      alreadyMember: 'Already a member?',
      registerLink: 'Register Now',
      loginLink: 'Log In Now',
      emailLabel: 'Email Address',
      emailPlaceholder: 'name@company.com',
      passwordLabel: 'Password',
      passwordPlaceholder: '••••••••',
      forgotPassword: 'Forgot Password?',
      submitLogin: 'Log In',
      submitSignup: 'Sign Up',
      continueGoogle: 'Continue with Google',
      continueFacebook: 'Continue with Facebook',
      continueApple: 'Continue with Apple',
      continueVK: 'Continue with VK',
      leftHeadline: 'Thousands of free samples, right at your fingertips',
      getAppButton: 'Get the App',
      roleBuyer: 'I am a Buyer',
      roleSeller: 'I am a Seller'
    },
    seller: {
      dashboard: 'Seller Hub',
      overview: 'Overview',
      products: 'Products',
      orders: 'Orders',
      analytics: 'Analytics',
      settings: 'Settings',
      createProduct: 'Create Product',
      productTitle: 'Product Title',
      productDesc: 'Description',
      uploadMedia: 'Upload Media',
      uploadHint: 'Supports JPG, PNG, MP4',
      quantity: 'Quantity',
      platformLinks: 'Platform Links',
      ozonLink: 'Ozon Link',
      wbLink: 'Wildberries Link',
      reviewReq: 'Review Requirements',
      reqPhoto: 'Photo Required',
      reqVideo: 'Video Required',
      publish: 'Publish',
      cancel: 'Cancel',
      activeProducts: 'Active Products',
      totalReviews: 'Total Reviews',
      reviewRate: 'Review Rate',
      pendingOrders: 'Pending Orders',
      customerRating: 'Customer Rating',
      recentProducts: 'Recent Products',
      status: 'Status',
      actions: 'Actions',
      viewReviews: 'View Reviews',
      shipBy: 'Ship By',
      markShipped: 'Mark Shipped',
      profileSettings: 'Shop Profile',
      shopName: 'Shop Name',
      shopNamePlaceholder: 'e.g. Best Beauty Shop',
      contactEmail: 'Contact Email',
      phoneNumber: 'Phone Number',
      saveChanges: 'Save Changes',
      security: 'Security',
      changePassword: 'Change Password',
      notifications: 'Notifications',
      traffic: 'Traffic Stats',
      conversionRate: 'Conversion Rate',
      dailyViews: 'Daily Views',
      recentReviews: 'Recent Reviews',
      ratingDistribution: 'Rating Dist.',
      topProducts: 'Top Products',
      totalViews: 'Total Views',
      sampleRequests: 'Sample Requests',
      avgRating: 'Avg. Rating',
      currentPassword: 'Current Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm Password',
      orderUpdates: 'Order Updates',
      reviewAlerts: 'Review Alerts',
      marketingEmails: 'Marketing Emails',
      logout: 'Log Out',
      membership: 'Membership',
      planStatus: 'Current Plan',
      daysRemaining: 'Days Remaining',
      upgradeToPro: 'Upgrade to Pro',
      trialExpired: 'Trial Expired',
      paymentRequired: 'You need an active subscription to publish new products.',
      monthlyPlan: 'Monthly Plan',
      yearlyPlan: 'Yearly Plan',
      selectPayment: 'Select Payment Method',
      payNow: 'Pay Now',
      bestValue: 'Best Value',
      billingCycle: 'Billing Cycle',
      paymentMethods: {
        alipay: 'Alipay',
        wechat: 'WeChat Pay',
        card: 'Card'
      }
    },
    buyer: {
      dashboard: 'Buyer Hub',
      browse: 'Browse Samples',
      mySamples: 'My Samples',
      inbox: 'Inbox',
      settings: 'Settings',
      requestSample: 'Request Sample',
      confirmReceipt: 'Confirm Receipt',
      writeReview: 'Write Review',
      reviewBy: 'Review By',
      daysLeft: 'days left',
      overdue: 'Overdue',
      reviewed: 'Reviewed',
      outOfStock: 'Out of Stock',
      waitingShipment: 'Waiting for Shipment',
      welcomeBack: 'Welcome back',
      availableSamples: 'Available Samples',
      profile: 'My Profile',
      shippingAddress: 'Shipping Address',
      security: 'Security',
      notifications: 'Notifications',
      fullName: 'Full Name',
      displayName: 'Display Name',
      gender: 'Gender',
      birthDate: 'Date of Birth',
      bio: 'Bio',
      addressLine1: 'Address Line 1',
      city: 'City',
      state: 'State / Province',
      zipCode: 'Zip Code',
      country: 'Country',
      saveChanges: 'Save Changes',
      logout: 'Log Out'
    },
    categories: {
      beauty: 'Beauty & Personal Care',
      apparel: 'Apparel & Accessories',
      electronics: 'Electronics',
      home: 'Home & Garden',
      grocery: 'Grocery & Gourmet',
      vehicles: 'Automotive',
      toys: 'Toys & Games',
      sports: 'Sports & Outdoors',
      business: 'Office Products',
      pets: 'Pet Supplies',
      arts: 'Arts & Crafts',
      health: 'Health & Household',
      // Subcategories
      face: 'Face Care', makeup: 'Makeup', hair: 'Hair Care', korean: 'K-Beauty', body: 'Body Care', nails: 'Nail Art', men: 'Men\'s Grooming', devices: 'Beauty Devices', organic: 'Organic',
      women_clothing: 'Women\'s Clothing', men_clothing: 'Men\'s Clothing', kids_clothing: 'Kids', sportswear: 'Sportswear', underwear: 'Underwear', shoes: 'Shoes', winter: 'Winter Wear', bags: 'Bags', accessories: 'Accessories',
      smartphones: 'Smartphones', computers: 'Computers', audio: 'Audio', smartwatch: 'Wearables', camera: 'Cameras', gaming: 'Gaming', kitchen_appliances: 'Kitchen Appliances', home_appliances: 'Home Appliances', personal_care: 'Personal Care',
      bedding: 'Bedding', kitchenware: 'Kitchenware', storage: 'Storage', lighting: 'Lighting', decor: 'Decor', garden: 'Garden', bathroom: 'Bath', tools: 'Tools',
      snacks: 'Snacks', coffee_tea: 'Coffee & Tea', grain_oil: 'Pantry Staples', health_food: 'Health Food', canned: 'Canned Food', nuts: 'Nuts', baking: 'Baking', drinks: 'Beverages',
      car_electronics: 'Car Electronics', car_interior: 'Interior', cleaning: 'Car Care', repair_tools: 'Tools', oil: 'Fluids', motorcycle: 'Motorcycle',
      educational: 'Educational', dolls: 'Dolls', remote_control: 'RC Toys', outdoor_toys: 'Outdoor Play', puzzles: 'Puzzles', plush: 'Plush', creative: 'Arts & DIY', models: 'Models',
      fitness: 'Fitness', outdoor: 'Outdoor Gear', fishing: 'Fishing', team_sports: 'Team Sports', cycling: 'Cycling', swimming: 'Swimming', camping: 'Camping', yoga: 'Yoga',
      office_supplies: 'Supplies', equipment: 'Equipment', packaging: 'Packaging', furniture: 'Furniture', printing: 'Printing', stationery: 'Stationery',
      dog_food: 'Dog Food', cat_food: 'Cat Food', pet_toys: 'Toys', pet_health: 'Healthcare', aquarium: 'Aquarium', small_animals: 'Small Animals', grooming: 'Grooming', pet_clothes: 'Clothing',
      painting: 'Painting', sewing: 'Sewing', knitting: 'Knitting', jewelry_making: 'Jewelry Making', pottery: 'Pottery', scrapbooking: 'Scrapbooking',
      supplements: 'Supplements', first_aid: 'First Aid', medical_devices: 'Medical Devices', massage: 'Massage', optical: 'Vision', sexual_wellness: 'Sexual Wellness', mobility: 'Mobility Aids'
    }
  },
  [Language.RU]: {
    nav: {
      logo: 'RuSample',
      searchPlaceholder: 'Поиск товаров или категорий...',
      login: 'Войти',
      signup: 'Регистрация',
      categories: 'Категории'
    },
    hero: {
      headline: 'Связь с мировыми брендами, бесплатные пробники',
      subheadline: 'RuSample помогает брендам донести новые продукты до целевой аудитории. Присоединяйтесь к нашему сообществу.',
      ctaButton: 'Начать',
      badgeTrial: '14 дней бесплатно',
      badgeUsers: '10k+ пользователей'
    },
    search: {
      resultsFor: 'Результаты для',
      noResults: 'Ничего не найдено',
      total: 'Всего',
      results: 'результатов'
    },
    auth: {
      loginTitle: 'С возвращением',
      signupTitle: 'Создать аккаунт',
      notMember: 'Нет аккаунта?',
      alreadyMember: 'Уже есть аккаунт?',
      registerLink: 'Зарегистрироваться',
      loginLink: 'Войти',
      emailLabel: 'Email адрес',
      emailPlaceholder: 'name@company.com',
      passwordLabel: 'Пароль',
      passwordPlaceholder: '••••••••',
      forgotPassword: 'Забыли пароль?',
      submitLogin: 'Войти',
      submitSignup: 'Создать',
      continueGoogle: 'Войти через Google',
      continueFacebook: 'Войти через Facebook',
      continueApple: 'Войти через Apple',
      continueVK: 'Войти через VK',
      leftHeadline: 'Тысячи бесплатных образцов в вашем распоряжении',
      getAppButton: 'Скачать приложение',
      roleBuyer: 'Я Покупатель',
      roleSeller: 'Я Продавец'
    },
    seller: {
      dashboard: 'Кабинет Продавца',
      overview: 'Обзор',
      products: 'Товары',
      orders: 'Заказы',
      analytics: 'Аналитика',
      settings: 'Настройки',
      createProduct: 'Добавить товар',
      productTitle: 'Название товара',
      productDesc: 'Описание',
      uploadMedia: 'Медиафайлы',
      uploadHint: 'JPG, PNG, MP4',
      quantity: 'Количество',
      platformLinks: 'Ссылки на платформы',
      ozonLink: 'Ссылка на Ozon',
      wbLink: 'Ссылка на Wildberries',
      reviewReq: 'Требования к обзору',
      reqPhoto: 'Нужно фото',
      reqVideo: 'Нужно видео',
      publish: 'Опубликовать',
      cancel: 'Отмена',
      activeProducts: 'Активные товары',
      totalReviews: 'Всего отзывов',
      reviewRate: 'Процент отзывов',
      pendingOrders: 'Новые заказы',
      customerRating: 'Рейтинг покупателей',
      recentProducts: 'Недавние товары',
      status: 'Статус',
      actions: 'Действия',
      viewReviews: 'Отзывы',
      shipBy: 'Отправить до',
      markShipped: 'Отправлено',
      profileSettings: 'Профиль магазина',
      shopName: 'Название магазина',
      shopNamePlaceholder: 'Например: Best Beauty',
      contactEmail: 'Email для связи',
      phoneNumber: 'Номер телефона',
      saveChanges: 'Сохранить',
      security: 'Безопасность',
      changePassword: 'Сменить пароль',
      notifications: 'Уведомления',
      traffic: 'Статистика трафика',
      conversionRate: 'Конверсия',
      dailyViews: 'Просмотры (день)',
      recentReviews: 'Новые отзывы',
      ratingDistribution: 'Распределение оценок',
      topProducts: 'Топ товаров',
      totalViews: 'Всего просмотров',
      sampleRequests: 'Запросы образцов',
      avgRating: 'Сред. оценка',
      currentPassword: 'Текущий пароль',
      newPassword: 'Новый пароль',
      confirmPassword: 'Подтвердите пароль',
      orderUpdates: 'Обновления заказов',
      reviewAlerts: 'Уведомления об отзывах',
      marketingEmails: 'Маркетинговые письма',
      logout: 'Выйти',
      membership: 'Подписка',
      planStatus: 'Текущий план',
      daysRemaining: 'Дней осталось',
      upgradeToPro: 'Продлить подписку',
      trialExpired: 'Пробный период истек',
      paymentRequired: 'Для публикации новых товаров требуется активная подписка.',
      monthlyPlan: 'Месячный план',
      yearlyPlan: 'Годовой план',
      selectPayment: 'Выберите способ оплаты',
      payNow: 'Оплатить сейчас',
      bestValue: 'Выгодно',
      billingCycle: 'Платежный цикл',
      paymentMethods: {
        alipay: 'Alipay',
        wechat: 'WeChat Pay',
        card: 'Банковская карта'
      }
    },
    buyer: {
      dashboard: 'Кабинет Покупателя',
      browse: 'Обзор образцов',
      mySamples: 'Мои образцы',
      inbox: 'Входящие',
      settings: 'Настройки',
      requestSample: 'Запросить образец',
      confirmReceipt: 'Подтвердить получение',
      writeReview: 'Написать отзыв',
      reviewBy: 'Отзыв до',
      daysLeft: 'дней осталось',
      overdue: 'Просрочено',
      reviewed: 'Оценено',
      outOfStock: 'Нет в наличии',
      waitingShipment: 'Ожидает отправки',
      welcomeBack: 'С возвращением',
      availableSamples: 'Доступные образцы',
      profile: 'Мой профиль',
      shippingAddress: 'Адрес доставки',
      security: 'Безопасность',
      notifications: 'Уведомления',
      fullName: 'ФИО',
      displayName: 'Никнейм',
      gender: 'Пол',
      birthDate: 'Дата рождения',
      bio: 'О себе',
      addressLine1: 'Адрес (строка 1)',
      city: 'Город',
      state: 'Область/Край',
      zipCode: 'Индекс',
      country: 'Страна',
      saveChanges: 'Сохранить изменения',
      logout: 'Выйти'
    },
    categories: {
      beauty: 'Красота и уход',
      apparel: 'Одежда и аксессуары',
      electronics: 'Электроника',
      home: 'Дом и сад',
      grocery: 'Продукты питания',
      vehicles: 'Автотовары',
      toys: 'Игрушки',
      sports: 'Спорт и отдых',
      business: 'Офис и бизнес',
      pets: 'Зоотовары',
      arts: 'Творчество',
      health: 'Здоровье',
      // Subcategories
      face: 'Уход за лицом', makeup: 'Макияж', hair: 'Уход за волосами', korean: 'Корейская косметика', body: 'Уход за телом', nails: 'Маникюр', men: 'Мужской уход', devices: 'Аппараты', organic: 'Органика',
      women_clothing: 'Женская одежда', men_clothing: 'Мужская одежда', kids_clothing: 'Детская одежда', sportswear: 'Спортивная одежда', underwear: 'Белье', shoes: 'Обувь', winter: 'Зимняя одежда', bags: 'Сумки', accessories: 'Аксессуары',
      smartphones: 'Смартфоны', computers: 'Компьютеры', audio: 'Аудио', smartwatch: 'Смарт-часы', camera: 'Камеры', gaming: 'Гейминг', kitchen_appliances: 'Техника для кухни', home_appliances: 'Техника для дома', personal_care: 'Личная гигиена',
      bedding: 'Постельное белье', kitchenware: 'Посуда', storage: 'Хранение', lighting: 'Освещение', decor: 'Декор', garden: 'Сад и огород', bathroom: 'Ванная', tools: 'Инструменты',
      snacks: 'Снэки', coffee_tea: 'Чай и кофе', grain_oil: 'Бакалея', health_food: 'Здоровое питание', canned: 'Консервы', nuts: 'Орехи', baking: 'Выпечка', drinks: 'Напитки',
      car_electronics: 'Автоэлектроника', car_interior: 'Интерьер', cleaning: 'Уход за авто', repair_tools: 'Инструменты', oil: 'Масла', motorcycle: 'Мототовары',
      educational: 'Обучающие', dolls: 'Куклы', remote_control: 'Радиоуправляемые', outdoor_toys: 'Для улицы', puzzles: 'Пазлы', plush: 'Мягкие игрушки', creative: 'Творчество', models: 'Моделирование',
      fitness: 'Фитнес', outdoor: 'Туризм', fishing: 'Рыбалка', team_sports: 'Командные виды', cycling: 'Велоспорт', swimming: 'Плавание', camping: 'Кемпинг', yoga: 'Йога',
      office_supplies: 'Канцелярия', equipment: 'Оргтехника', packaging: 'Упаковка', furniture: 'Мебель', printing: 'Печать', stationery: 'Школьные товары',
      dog_food: 'Для собак', cat_food: 'Для кошек', pet_toys: 'Игрушки', pet_health: 'Здоровье', aquarium: 'Аквариумистика', small_animals: 'Грызуны', grooming: 'Груминг', pet_clothes: 'Одежда',
      painting: 'Рисование', sewing: 'Шитье', knitting: 'Вязание', jewelry_making: 'Украшения', pottery: 'Гончарство', scrapbooking: 'Скрапбукинг',
      supplements: 'БАДы', first_aid: 'Первая помощь', medical_devices: 'Медтехника', massage: 'Массаж', optical: 'Оптика', sexual_wellness: '18+', mobility: 'Реабилитация'
    }
  }
};